stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - sudo apt-get update
    - sudo --force-yes apt install docker.io
    - sudo --force-yes apt install docker-compose

deploy-job:
  stage: deploy
  script:
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/project
    - docker-compose up -d

