stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - sftp root@194.87.232.8:/root <<< $'put ./db
    - sftp root@194.87.232.8:/root <<< $'put ./httpd
    - sftp root@194.87.232.8:/root <<< $'put ./mariadb
    - sftp root@194.87.232.8:/root <<< $'put ./onlybro
    - sftp root@194.87.232.8:/root <<< $'put ./php
    - sftp root@194.87.232.8:/root <<< $'put ./docker-compose.yml

deploy-job:
  stage: deploy
  script:
   - ssh root@194.87.232.8 "docker-compose up --build"
