stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - sudo apt-get update
    - sudo  apt install docker.io
    - sudo  apt install docker-compose
test-job:
  stage: test
  script:
    - echo "hello world!"
deploy-job:
  stage: deploy
  script:
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/project 
    - docker-compose up

