stages:
  - build
  - deploy
build:
  stage: build
  script:
    - sftp root@kali:/root <<< $'put ./db
    - sftp root@kali:/root <<< $'put ./httpd
    - sftp root@kali:/root <<< $'put ./mariadb
    - sftp root@kali:/root <<< $'put ./onlybro
    - sftp root@kali:/root <<< $'put ./php
    - sftp root@kali:/root <<< $'put ./docker-compose.yml

deploy:
  stage: deploy
  script:
   - ssh root@kali "docker-compose up --build"
