stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - sftp root@ruvds-xb1ot:/root <<< $'put ./db
    - sftp root@ruvds-xb1ot:/root <<< $'put ./httpd
    - sftp root@ruvds-xb1ot:/root <<< $'put ./mariadb
    - sftp root@ruvds-xb1ot:/root <<< $'put ./onlybro
    - sftp root@ruvds-xb1ot:/root <<< $'put ./php
    - sftp root@ruvds-xb1ot:/root <<< $'put ./docker-compose.yml

deploy-job:
  stage: deploy
  script:
   - ssh root@ruvds-xb1ot "cd /docker-compose up --build"
