stages:
  - build

build-job:
  stage: build
  script:
    - apt-get update
    - apt-get --force-yes -y install rsync
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/project

