stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - sftp root@185.217.119.35:/root <<< $'put ./db
    - sftp root@185.217.119.35t:/root <<< $'put ./httpd
    - sftp root@185.217.119.35:/root <<< $'put ./mariadb
    - sftp root@185.217.119.35:/root <<< $'put ./onlybro
    - sftp root@185.217.119.35:/root <<< $'put ./php
    - sftp root@185.217.119.35:/root <<< $'put ./docker-compose.yml

deploy-job:
  stage: deploy
  script:
   - ssh root@185.217.119.35 "cd /Project|docker-compose up --build"
