stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - apt-get update
    - apt-get --force-yes -y install rsync
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /home/deploy

deploy-job:
  stage: deploy
  script:
   - ssh root@193.104.57.249 "docker-compose up --build"


