stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - rsynk root@193.104.57.249:/root <<< $'put ./httpd
    - rsynk root@193.104.57.249:/root <<< $'put ./000-default
    - rsynk root@193.104.57.249:/root <<< $'put ./apache2.conf
    - rsynk root@193.104.57.249:/root <<< $'put ./mariadb
    - rsynk root@193.104.57.249:/root <<< $'put ./onlybro
    - rsynk root@193.104.57.249:/root <<< $'put ./docker-compose.yml

deploy-job:
  stage: deploy
  script:
   - ssh root@193.104.57.249 "docker-compose up --build"


