stages:
  - build
  # - test
  - deploy
 # - scan
  - secrets


build-job:
  stage: build
  script:
    - apt-get update
    - apt install docker.io
    - apt install docker-compose
    # - cd ./sonarqube
    # - docker-compose up -d
  

# test-job:
#   stage: test
#   script:
#     - cd ./sonarqube/sonar-scanner
#     - docker-compose up 
#     - docker run -v /home/gitlab-runner/builds/cAcgUEf_/0/ivanantonovjobs/onlybro/:/usr/src sonarsource/sonar-scanner-cli -Dsonar.projectKey=only-bro -Dsonar.sources=. -Dsonar.host.url=http://176.113.83.63:9000 -Dsonar.login=sqp_ade41f2c61fe00cbdb542db71729af3b92f46bfd

deploy-job:
  stage: deploy
  script:
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/project 
    - docker-compose up -d

# scan-job: 
#   stage: scan
#   image:
#     name: owasp/zap2docker-stable 
#   before_script:
#     - mkdir -p /zap/wrk
#   script:
#       - pwd
#       - ls
#       - docker run -v /zap/wrk:/zap/wrk:rw --user root owasp/zap2docker-stable zap-full-scan.py -t "http://176.113.83.63:8080" -I -r testreport.html
#       - cp /zap/wrk/testreport.html testreport.html
#   artifacts:
#     when: always
#     paths:
#       - testreport.html

trufflehog:
  stage: secrets
  image: python:3-alpine
  script: docker run -v /home/gitlab-runner/builds/cAcgUEf_/0/ivanantonovjobs/onlybro/:/home/gitlab-runner/builds/cAcgUEf_/0/ivanantonovjobs/onlybro/ --user root python:latest | apk add --no-cache git | pip install trufflehog | adduser -S truffleHog | trufflehog --entropy true file://home/gitlab-runner/builds/cAcgUEf_/0/ivanantonovjobs/onlybro/     
    
