stages:
  - build
#  - test
  - deploy

build-job:
  stage: build
  script:
    - sudo apt-get update
    - sudo  apt install docker.io
    - sudo  apt install docker-compose
    - cd ./sonarqube
    - docker-compose up

# test-job:
#   stage: test
#   script:
#     - docker run \
#      --rm \
#      -e SONAR_HOST_URL="http://193.104.57.249:9000" \
#      -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=${YOUR_PROJECT_KEY}"
#      -e SONAR_LOGIN="myAuthenticationToken" \
#      -v "${YOUR_REPO}:/usr/src" \
#      sonarsource/sonar-scanner-cli

deploy-job:
  stage: deploy
  script:
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/project 
    - docker-compose up

