image: docker:latest

stages:
  - deploy

deploy-job:
  stage: deploy
  script:
    - apt-get update
    - apt-get --force-yes -y install rsync
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/project 
    - docker-compose --build