stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - sftp root@193.104.57.249:/root <<< $'put ./db
    - sftp root@193.104.57.249:/root <<< $'put ./httpd
    - sftp root@193.104.57.249:/root <<< $'put ./mariadb
    - sftp root@193.104.57.249:/root <<< $'put ./onlybro
    - sftp root@193.104.57.249:/root <<< $'put ./php
    - sftp root@193.104.57.249:/root <<< $'put ./docker-compose.yml

deploy-job:
  stage: deploy
  script:
   - ssh root@193.104.57.249 "cd /docker-compose up --build"
