version: '3'

services:
  apache:
    image: httpd:latest
    volumes:
      - ./onlybro:/var/www/html
      - ./000-default/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2.conf:/etc/apache2.conf
    depends_on:
      - php
    expose:
      - "8080"
      - "80" 

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80  
    volumes:
      - ./onlybro:/var/www/html
    depends_on:
      - mariadb
  

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mariadb
      
  sonarqube:
    image: sonarqube:8.9.2-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar #tochange
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:80"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar #tochange
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
