version: '3'

services:
  apache:
    image: httpd:latest
    volumes:
      - ./onlybro:/var/www/html
      - ./000-default/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2.conf:/etc/apache2.conf
    depends_on:
      - php
    expose:
      - "8080"
      - "80" 

  php:
    build:
      context: ./
      dockerfile: Dockerfile  
    ports:
      - 8080:80  
    volumes:
      - ./onlybro:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
    ports: 
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mariadb
